config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :doors
  end

  get 'escape_route' => 'escape_routes#index'

  root 'floors#index'

  resources :floors

end

app/models/door.rb
class Door < ActiveRecord::Base
  belongs_to :room
  belongs_to :with, :class_name => "Room", :foreign_key => "with_id"

  validates :room, :position, :left, :top, presence: true
  validates :position, inclusion: {in: %w(top left right bottom)}

end

app/models/escape_route.rb
class EscapeRoute

  attr_reader :min_route, :link_matrix

  def initialize(floor)
    @floor = floor
    @rooms = floor.rooms
  end

  # expect room ids as params
  def build_route(from, to)
    build_link_matrix!
    find_min_route(from, to)
  end

  # private

  def find_min_route(from, to)
    @min_route = []
    @min_cost = 100000
    dfs(from, to, [from])
    @min_route
  end

  def dfs(from, to, route)
    if from.id == to.id
      if cost(route) < @min_cost
        @min_cost = cost(route)
        @min_route = route.dup
      end
      return
    end

    @link_matrix[from.id].each do |room|
      next if route.include?(room)
      route << room
      dfs(room, to, route)
      route.delete(room)
    end
  end

  def build_link_matrix!
    @link_matrix = {}

    @rooms.each do |room|
      @link_matrix[room.id] = []
      @rooms.each do |neighbour_candidate|
        if rooms_linked?(room, neighbour_candidate)
          @link_matrix[room.id] << neighbour_candidate
        end
      end
    end
  end

  def rooms_linked?(a, b)
    a.neighbours.include?(b) || b.neighbours.include?(a)
  end

  def cost(route)
    route.inject(0) {|sum, room| sum + room.danger_level*2}
  end

  def readable_link_matrix
    matrix = {}
    @link_matrix.each do |key, values|
      matrix[key] = values.map(&:id)
    end
    matrix
  end

end

app/models/floor.rb
class Floor < ActiveRecord::Base
  has_many :rooms
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :floor
  has_many :doors

  # types: 'взрывоопасный', 'пожароопасный', 'малоопасный', 'негорючий'
  CONTAINER_TYPES = %w(safe little fire explosive)
  validates :containers_type, inclusion: {in: CONTAINER_TYPES}

  def right
    left+width
  end

  def bottom
    top+length
  end

  def neighbours
    if doors.present?
      doors.includes(:with).map(&:with).compact
    else
      Room.none
    end
  end

  def to_s
    "Room-#{id}"
  end

  def has_left_door?
    doors.where(position: 'left').present?
  end

  def has_right_door?
    doors.where(position: 'right').present?
  end

  def has_top_door?
    doors.where(position: 'top').present?
  end

  def has_bottom_door?
    doors.where(position: 'bottom').present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doors_controller.rb
class DoorsController < ApplicationController
  before_action :set_room
  before_action :set_door, only: [:show, :edit, :update, :destroy]

  # GET /doors
  def index
    @doors = @room.doors
  end

  # GET /doors/1
  def show
  end

  # GET /doors/new
  def new
    @door = @room.doors.build(top: 20, left: 20)
  end

  # GET /doors/1/edit
  def edit
  end

  # POST /doors
  def create
    @door = Door.new(door_params)

    if @door.save
      redirect_to [@room, :doors], notice: 'Door was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /doors/1
  def update
    if @door.update(door_params)
      redirect_to [@room, :doors], notice: 'Door was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /doors/1
  def destroy
    @door.destroy
    redirect_to [@room, :doors], notice: 'Door was successfully destroyed.'
  end

  private
    def set_room
      @room = Room.find(params[:room_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_door
      @door = Door.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def door_params
      params.require(:door).permit(:position, :room_id, :with_id, :top, :left)
    end
end

app/controllers/escape_routes_controller.rb
class EscapeRoutesController < ApplicationController
  def index
    from = Room.find(params[:from].to_i)
    to = Room.find(params[:to].to_i)
    route_builder = EscapeRoute.new(Floor.first)
    @route = route_builder.build_route(from, to)
    render layout: false
  end
end

app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: [:show, :edit, :update, :destroy]
  before_action :set_active_menu_item

  def index
    @floors = Floor.order(:created_at)
  end

  def show
  end

  def new
    @floor = Floor.new
  end

  def edit
  end

  def create
    @floor = Floor.new(floor_params)

    if @floor.save
      redirect_to @floor, notice: 'Warehouse was successfully created.'
    else
      render :new
    end
  end

  def update
    if @floor.update(floor_params)
      redirect_to @floor, notice: 'Warehouse was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @floor.destroy
    redirect_to floors_url, notice: 'Warehouse was successfully destroyed.'
  end

  private
    def set_floor
      @floor = Floor.find(params[:id])
    end

    def floor_params
      params.require(:floor).permit(:name, :width, :length)
    end

    def set_active_menu_item
      @active_menu_item = :floors
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :set_active_menu_item

  def index
    @rooms = Room.order('created_at')
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to rooms_path, notice: 'Room was successfully created.'
    else
      render :new
    end
  end

  def update
    if @room.update(room_params)
      update_danger_level(@room)
      redirect_to @room.floor, notice: 'Room was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(
        :floor_id,
        :width,
        :length,
        :top,
        :left,
        :containers_count,
        :containers_type,
        :has_left_door,
        :has_right_door,
        :has_top_door,
        :has_bottom_door,
        :danger_level
      )
    end

    def set_active_menu_item
      @active_menu_item = :rooms
    end

    def update_danger_level(room)
      input_file = '/Users/sky/Documents/MATLAB/input1.txt'
      output_file = '/Users/sky/Documents/MATLAB/output1.txt'

      File.open(input_file, 'w') do |file|
        danger_level = Room::CONTAINER_TYPES.reverse.index(room.containers_type) + 1

        file.puts(danger_level) # тип склада
        file.puts(room.width * room.length * 50) # площадь
        file.puts(room.floor.rooms.size) # количество комнат
        file.puts(room.containers_count)
      end
      # `matlab -nodisplay -nojvm -r "calc_danger_level('#{input_file}', '#{output_file}'); exit"`
      `cd /Users/sky/Documents/MATLAB && matlab -nodisplay -nojvm -r "fire(1); exit"`
      danger_level = File.read(output_file).to_i
      room.update(danger_level: danger_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu_link(name, url=nil, options={})
    options = options.dup
    active_item = options.delete(:active_item) || @active_menu_item
    i18n_scope = options.delete(:menu_code) || 'main_menu'
    text = options.delete(:text) || t(name, scope: i18n_scope)

    css_class = 'menu-link'
    css_class << ' active' if active_item == name
    content_tag :li, class: css_class do
      link_to text, url, options
    end
  end

  def mult
    30
  end

  def container_glyphicon_class(room)
    case room.containers_type
    when 'safe'
      'glyphicon-hdd'
    when 'little'
      'glyphicon-tree-conifer'
    when 'fire'
      'glyphicon-warning-sign'
    when 'explosive'
      'glyphicon-flash'
    end
  end

  def room_bg_class(room)
    ['bg-normal', 'bg-info', 'bg-warning', 'bg-danger'][room.danger_level]
  end
end

app/helpers/doors_helper.rb
module DoorsHelper
end

app/helpers/floors_helper.rb
module FloorsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/doors/_form.html.haml
.row
  .col-md-4
    = simple_form_for [@room, @door] do |f|
      = f.input :room_id, as: :hidden

      = f.association :with, collection: @room.floor.rooms.where("id <> #{@room.id}").order(:id)

      = f.input :position, as: :select, collection: %w(top left right bottom), include_blank: false

      = f.input :left

      = f.input :top

      .buffer-20
      = f.button :submit

app/views/doors/edit.html.haml
%h1 Editing door

= render 'form'

= link_to 'Back', room_doors_path(@room)

app/views/doors/index.html.haml
%h1 Listing doors

- if @room.neighbours.present?
  %p= "Has doors with rooms #{@room.neighbours.map(&:id).join(', ')}."

%table.table
  %tr
    %th Position
    %th
    %th

  - @doors.each do |door|
    %tr
      %td= door.position
      %td= link_to 'Edit', edit_room_door_path(@room, door)
      %td= link_to 'Destroy', [@room, door], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Door', new_room_door_path(@room)

app/views/doors/new.html.haml
%h1 New door

= render 'form'

= link_to 'Back', room_doors_path(@room)

app/views/doors/show.html.haml
%p#notice= notice

%p
  %b Outer:
  = @door.outer
%p
  %b Position:
  = @door.position
%p
  %b Room:
  = @door.room

= link_to 'Edit', edit_door_path(@door)
\|
= link_to 'Back', doors_path

app/views/escape_routes/index.html.haml
%h5 Most safest route
= @route.map(&:to_s).join(' -> ')

app/views/floors/_form.html.haml
.row
  .col-md-6
    = simple_form_for @floor do |f|
      = f.input :name
      = f.input :width
      = f.input :length

      .buffer-20
      = f.button :submit, 'Save'

app/views/floors/edit.html.haml
%h1 Editing warehouse

= render 'form'

= link_to 'Show', @floor
\|
= link_to 'Back', floors_path

app/views/floors/index.html.haml
%h1 Listing warehouses

%table.table
  %tr
    %th Name
    %th Width
    %th Length
    %th
    %th

  - @floors.each do |floor|
    %tr
      %td= link_to floor.name, floor
      %td= floor.width
      %td= floor.length
      %td= link_to 'Edit', edit_floor_path(floor)
      %td= link_to 'Destroy', floor, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New warehouse', new_floor_path

app/views/floors/new.html.haml
%h1 New warehouse

= render 'form'

= link_to 'Back', floors_path

app/views/floors/show.html.haml
%h2= @floor.name

:sass
  .floor-schema
    width: #{@floor.width * mult}px
    height: #{@floor.length * mult}px


.floor-schema
  - @floor.rooms.each_with_index do |room, i|
    = render room, i: i


.buffer-40
%h3 Build escape route

= form_tag '/escape_route', method: :get, class: 'form-horizontal', remote: true, id: 'route-form' do
  .row
    .col-md-3
      %label.control-label From
      = select_tag "from", options_from_collection_for_select(@floor.rooms.order(:id), "id", "to_s", selected: 2), class: 'form-control'
    .col-md-3
      %label.control-label To
      = select_tag "to", options_from_collection_for_select(@floor.rooms.order(:id), "id", "to_s", selected: 3), class: 'form-control'

  = submit_tag 'FIRE! Build escape route immediately!', class: 'btn btn-danger btn-lg start-fire-button buffer-20'

  .route-container

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Меню
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Fire danger analyzer', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = menu_link :floors, floors_path
        = menu_link :rooms, rooms_path

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}
  %head
    :plain
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
    %title Floors

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'

  %body
    = render 'layouts/nav'
    .container
      = render 'layouts/messages'
      = yield

app/views/rooms/_form.html.haml
.row
  .col-md-6
    = simple_form_for @room do |f|
      = f.association :floor
      = f.input :width
      = f.input :length
      = f.input :top
      = f.input :left

      .buffer-20
      = f.button :submit

app/views/rooms/_room.html.haml
:sass
  ##{"room-" + room.id.to_s}
    width: #{room.width * mult}px
    height: #{room.length * mult}px
    top: #{room.top * mult}px
    left: #{room.left * mult}px

.room-container{id: "room-#{room.id}", class: room_bg_class(room)}
  %h5.room-id= "Room-#{room.id}"
  %a.glyphicon.glyphicon-cog{href: '#'}
  .containers
    - room.containers_count.times do
      .container-icon.glyphicon{class: container_glyphicon_class(room)}

  .door.door-left{class: ('hidden' unless room.has_left_door?)}
  .door.door-right{class: ('hidden' unless room.has_right_door?)}
  .door.door-top{class: ('hidden' unless room.has_top_door?)}
  .door.door-bottom{class: ('hidden' unless room.has_bottom_door?)}

  .modal.fade(tabindex="-1")
    .modal-dialog.modal-lg
      .modal-content
        .modal-body
          .row
            .col-md-6
              = simple_form_for room do |f|
                = f.input :containers_type, as: :select, collection: %w(safe little fire explosive), include_blank: false, label: 'Containers danger class'

                = f.input :containers_count

                .buffer-20
                = f.button :submit

app/views/rooms/edit.html.haml
%h1 Editing room

= render 'form'

= link_to 'Show', @room
\|
= link_to 'Back', rooms_path

app/views/rooms/index.html.haml
%h1 Listing rooms

%table.table
  %tr
    %th Name
    %th Floor
    %th Width
    %th Length
    %th Top
    %th Left
    -# %th
    %th
    %th

  - @rooms.each do |room|
    %tr
      %td= room.to_s
      %td= link_to room.floor.name, room.floor
      %td= room.width
      %td= room.length
      %td= room.top
      %td= room.left
      %td
        = link_to room_doors_path(room) do
          = "Doors (#{room.doors.count})"
      %td= link_to 'Edit', edit_room_path(room)
      %td= link_to 'Destroy', room, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Room', new_room_path

app/views/rooms/new.html.haml
%h1 New room

= render 'form'

= link_to 'Back', rooms_path

app/views/rooms/show.html.haml
%p#notice= notice

%p
  %b Floor:
  = @room.floor.name
%p
  %b Width:
  = @room.width
%p
  %b Length:
  = @room.length
%p
  %b Top:
  = @room.top

= link_to 'Edit', edit_room_path(@room)
\|
= link_to 'Back', rooms_path